name: Build OrangeFox A15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Environment Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip python3
        
    - name: Clone OrangeFox Source & Device Tree
      run: |
        mkdir fox && cd fox
        repo init -u https://gitlab.com/OrangeFox/sync.git -b master
        # Menggunakan branch a15 karena berisi file dtb dan omni_zircon.mk
        git clone https://github.com/handokocici-87/android_device_xiaomi_zircon_twrp.git -b a15 device/xiaomi/zircon
        
    - name: Sync & Build
      run: |
        cd fox
        source build/envsetup.sh
        lunch omni_zircon-eng
        mka adbd recoveryimage
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-Recovery
        path: fox/out/target/product/zircon/recovery.img
        
